//
//  DotenvTransfer.swift
//  hyperenv
//
//  Import and export of `.env` files.
//

import AppKit
import SwiftUI

@MainActor
@Observable
final class DotenvTransfer {

    struct PendingImport: Identifiable {
        let id = UUID()
        let fileName: String
        let result: DotenvDecodeResult
    }

    struct PendingOverwrite: Identifiable {
        let id = UUID()
        let url: URL
        let text: String
    }

    var pendingImport: PendingImport?
    var pendingOverwrite: PendingOverwrite? {
        didSet { showsAlert = pendingOverwrite != nil }
    }

    var showsAlert = false
    var alertTitle = ""
    var alertMessage = ""

    // MARK: Export

    /// Which of a profile's variables an export should carry.
    ///
    /// The distinction exists because "switched on" means "safe to replay into a
    /// shell", not "not worth exporting". The snapshot profile switches almost
    /// everything off — a search path or a session socket must never be applied
    /// — yet exporting it to read or to hand over is a reasonable thing to want,
    /// and exporting only the enabled ones produced a file with no variables in
    /// it at all.
    enum Scope: String, CaseIterable, Identifiable {
        case enabledOnly
        case everything

        var id: String { rawValue }

        var label: String {
            switch self {
            case .enabledOnly: "Switched On"
            case .everything: "All Variables"
            }
        }

        var summary: String {
            switch self {
            case .enabledOnly: "Only what this profile would apply."
            case .everything: "Every variable listed, switched off ones included."
            }
        }
    }

    /// Explains an empty export instead of writing an empty file.
    private func reportNothingToExport(profile: Profile, scope: Scope) {
        let total = profile.variables.count
        alertTitle = "Nothing to export"

        if total == 0 {
            alertMessage = "\(profile.name) has no variables yet."
        } else if scope == .enabledOnly {
            alertMessage = """
                None of the \(total) variables in \(profile.name) are switched on, so this \
                would write a file with no variables in it.

                Pick "All Variables" from the export menu to write every one of them, or \
                switch on the ones you want first.
                """
        } else {
            // Every key was rejected by EnvKey, which only happens if they are
            // all blank or not valid shell names.
            alertMessage = "None of the \(total) variables in \(profile.name) have a name the shell can export."
        }

        showsAlert = true
    }

    /// The variables an export of this scope would carry.
    ///
    /// Separate from `export` so it can be checked without a save panel. The bug
    /// it exists for — a snapshot profile exporting to a file containing only
    /// comments — is invisible unless something inspects the contents.
    static func variables(of profile: Profile, scope: Scope) -> EnvSet {
        var set = EnvSet()
        for variable in profile.sortedVariables {
            guard scope == .everything || variable.isEnabled else { continue }
            guard let key = variable.envKey else { continue }
            set[key] = EnvValue(variable.value)
        }
        return set
    }

    /// The file's contents, or `nil` when there is nothing worth writing — in
    /// which case the alert has been prepared and the caller should stop.
    func exportText(
        profile: Profile,
        dialect: DotenvDialect,
        scope: Scope
    ) -> (text: String, diagnostics: [DotenvDiagnostic])? {
        let set = Self.variables(of: profile, scope: scope)

        // Writing a file that holds nothing but a comment header is the failure
        // this guards against: it looks like a successful export right up until
        // the file is opened.
        guard !set.isEmpty else {
            reportNothingToExport(profile: profile, scope: scope)
            return nil
        }

        let scopeNote = scope == .everything
            ? "All \(set.count) variables, including ones this profile does not apply."
            : "The \(set.count) variables this profile applies."
        let header = [
            "Generated by HyperEnv",
            "Project: \(profile.project?.name ?? "—")  Profile: \(profile.name)",
            scopeNote,
            "Contains secrets — do not commit this file.",
        ]
        return DotenvCodec.encode(set, dialect: dialect, headerComment: header)
    }

    func export(profile: Profile, dialect: DotenvDialect, scope: Scope = .enabledOnly) {
        guard let (text, diagnostics) = exportText(
            profile: profile, dialect: dialect, scope: scope) else { return }

        let panel = NSSavePanel()
        panel.nameFieldStringValue = ".env.\(profile.name.lowercased())"
        panel.message = "Export \(profile.name) as \(dialect.displayName)"
        panel.canCreateDirectories = true

        if let folder = profile.project?.folderPath {
            panel.directoryURL = URL(fileURLWithPath: folder)
        }

        guard panel.runModal() == .OK, let url = panel.url else { return }

        // NSSavePanel already confirms replacement, but a `.env` in a project
        // folder usually holds live credentials, so the previous contents are
        // preserved before anything is written.
        if FileManager.default.fileExists(atPath: url.path(percentEncoded: false)) {
            pendingOverwrite = PendingOverwrite(url: url, text: text)
            alertTitle = "Replace \(url.lastPathComponent)?"
            alertMessage = "The current contents will be copied to \(url.lastPathComponent).bak first."
            return
        }

        write(text, to: url, extraWarnings: diagnostics)
    }

    func commitOverwrite(_ pending: PendingOverwrite) {
        let backup = pending.url.appendingPathExtension("bak")
        try? FileManager.default.removeItem(at: backup)
        try? FileManager.default.copyItem(at: pending.url, to: backup)

        pendingOverwrite = nil
        write(pending.text, to: pending.url, extraWarnings: [])
    }

    private func write(_ text: String, to url: URL, extraWarnings: [DotenvDiagnostic]) {
        do {
            try text.write(to: url, atomically: true, encoding: .utf8)
            try? FileManager.default.setAttributes(
                [.posixPermissions: NSNumber(value: Int16(0o600))],
                ofItemAtPath: url.path(percentEncoded: false))

            var notes = extraWarnings.map(\.message)
            if let warning = gitignoreWarning(for: url) { notes.append(warning) }

            alertTitle = "Exported"
            alertMessage = notes.isEmpty
                ? "Written to \(Paths.displayPath(url))."
                : ("Written to \(Paths.displayPath(url)).\n\n" + notes.joined(separator: "\n"))
            showsAlert = true
        } catch {
            alertTitle = "Export failed"
            alertMessage = error.localizedDescription
            showsAlert = true
        }
    }

    /// Cheap check with high payoff: an exported `.env` that git is not
    /// ignoring is a credential leak waiting to be committed.
    private func gitignoreWarning(for url: URL) -> String? {
        let folder = url.deletingLastPathComponent()
        let gitignore = folder.appending(path: ".gitignore")
        let isRepo = FileManager.default.fileExists(
            atPath: folder.appending(path: ".git").path(percentEncoded: false))
        guard isRepo else { return nil }

        guard let contents = try? String(contentsOf: gitignore, encoding: .utf8) else {
            return "⚠︎ This folder is a git repository with no .gitignore. Add one before committing."
        }

        let covered = contents.split(separator: "\n").contains { line in
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            return trimmed == ".env" || trimmed == ".env*" || trimmed == "*.env"
                || trimmed == url.lastPathComponent
        }
        return covered ? nil : "⚠︎ .gitignore does not appear to cover this file."
    }

    // MARK: Import

    func beginImport() {
        let panel = NSOpenPanel()
        panel.canChooseFiles = true
        panel.canChooseDirectories = false
        panel.allowsMultipleSelection = false
        panel.message = "Choose a .env file to import"
        panel.showsHiddenFiles = true

        guard panel.runModal() == .OK, let url = panel.url else { return }

        do {
            let text = try String(contentsOf: url, encoding: .utf8)
            pendingImport = PendingImport(
                fileName: url.lastPathComponent,
                result: DotenvCodec.decode(text))
        } catch {
            alertTitle = "Could not read that file"
            alertMessage = "\(url.lastPathComponent) is not valid UTF-8 text."
            showsAlert = true
        }
    }
}

// MARK: - Import preview

struct ImportPreviewSheet: View {
    let pending: DotenvTransfer.PendingImport
    var onCommit: ([DotenvEntry]) -> Void

    @Environment(\.dismiss) private var dismiss
    @State private var excluded: Set<String> = []

    private var included: [DotenvEntry] {
        pending.result.entries.filter { !excluded.contains($0.key.rawValue) }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            VStack(alignment: .leading, spacing: 4) {
                Text("Import \(pending.fileName)").font(.headline)
                // Shown before committing because a `#` inside an unquoted
                // value is ambiguous and can silently truncate what gets
                // imported — the user should see the parse, not trust it.
                Text("Review what HyperEnv read from the file.")
                    .font(.caption).foregroundStyle(.secondary)
            }
            .padding(16)

            Divider()

            if pending.result.entries.isEmpty {
                ContentUnavailableView(
                    "Nothing to import", systemImage: "doc.text",
                    description: Text("No valid assignments were found."))
                    .frame(height: 180)
            } else {
                List {
                    ForEach(pending.result.entries, id: \.key.rawValue) { entry in
                        HStack(spacing: 10) {
                            Toggle("", isOn: .init(
                                get: { !excluded.contains(entry.key.rawValue) },
                                set: { keep in
                                    if keep { excluded.remove(entry.key.rawValue) }
                                    else { excluded.insert(entry.key.rawValue) }
                                }))
                            .labelsHidden()

                            Text(entry.key.rawValue)
                                .font(.system(.body, design: .monospaced))
                                .frame(width: 190, alignment: .leading)

                            Text(entry.value.rawValue.isEmpty ? "(empty)" : entry.value.rawValue)
                                .font(.system(.body, design: .monospaced))
                                .foregroundStyle(entry.value.isEmpty ? .secondary : .primary)
                                .lineLimit(1)

                            Spacer()
                            Text("line \(entry.line)")
                                .font(.caption2).foregroundStyle(.tertiary)
                        }
                    }
                }
                .frame(height: 240)
            }

            if !pending.result.diagnostics.isEmpty {
                Divider()
                ScrollView {
                    VStack(alignment: .leading, spacing: 4) {
                        ForEach(pending.result.diagnostics) { diagnostic in
                            HStack(alignment: .top, spacing: 6) {
                                Image(systemName: diagnostic.severity == .error
                                      ? "xmark.octagon.fill" : "exclamationmark.triangle.fill")
                                    .foregroundStyle(diagnostic.severity == .error ? .red : .orange)
                                    .font(.caption)
                                Text("Line \(diagnostic.line): \(diagnostic.message)")
                                    .font(.caption)
                                Spacer()
                            }
                        }
                    }
                    .padding(12)
                }
                .frame(maxHeight: 110)
            }

            Divider()

            HStack {
                Text("\(included.count) of \(pending.result.entries.count) selected")
                    .font(.caption).foregroundStyle(.secondary)
                Spacer()
                Button("Cancel") { dismiss() }
                Button("Import") {
                    onCommit(included)
                    dismiss()
                }
                .buttonStyle(.glassProminent)
                .disabled(included.isEmpty)
            }
            .padding(16)
        }
        .frame(width: 620)
    }
}
