//
//  Brand.swift
//  hyperenv
//
//  GENERATED by Scripts/generate-app-icon.swift — do not edit by hand.
//
//  The icon's palette, available to the interface. The plate gradient is the
//  app's identity; the three dots are the environment classes, and those are
//  declared in ProfileStyle where their meaning lives.
//
//  Identity colour is deliberately kept off anything that signals risk. The
//  question this app exists to answer is which environment is live, and a brand
//  colour spread across that signal would dilute it.
//

import SwiftUI

nonisolated enum Brand {
    static let plateTop = Color(
        .sRGB, red: 0.286, green: 0.361, blue: 0.949)
    static let plateBottom = Color(
        .sRGB, red: 0.435, green: 0.176, blue: 0.855)
    static let accent = Color(
        .sRGB, red: 0.360, green: 0.268, blue: 0.902)

    // The three dots on the icon. ProfileStyle gives them their meaning; this
    // is only where the numbers live, so a badge and a dot cannot disagree.
    static let development = Color(
        .sRGB, red: 0.204, green: 0.780, blue: 0.349)
    static let homologation = Color(
        .sRGB, red: 1.000, green: 0.624, blue: 0.039)
    static let production = Color(
        .sRGB, red: 1.000, green: 0.271, blue: 0.227)

    /// The plate, as it appears on the icon.
    static let gradient = LinearGradient(
        colors: [plateTop, plateBottom],
        startPoint: .topLeading,
        endPoint: .bottomTrailing)

    /// A wash faint enough to sit behind text.
    static func tint(_ opacity: Double) -> LinearGradient {
        LinearGradient(
            colors: [plateTop.opacity(opacity), plateBottom.opacity(opacity)],
            startPoint: .topLeading,
            endPoint: .bottomTrailing)
    }
}
