//
//  DotenvTransfer.swift
//  hyperenv
//
//  Import and export of `.env` files.
//

import AppKit
import SwiftUI

@MainActor
@Observable
final class DotenvTransfer {

    struct PendingImport: Identifiable {
        let id = UUID()
        let fileName: String
        let result: DotenvDecodeResult
    }

    struct PendingOverwrite: Identifiable {
        let id = UUID()
        let url: URL
        let text: String
    }

    var pendingImport: PendingImport?
    var pendingOverwrite: PendingOverwrite? {
        didSet { showsAlert = pendingOverwrite != nil }
    }

    var showsAlert = false
    var alertTitle = ""
    var alertMessage = ""

    // MARK: Export

    func export(profile: Profile, dialect: DotenvDialect) {
        var set = EnvSet()
        for variable in profile.sortedVariables where variable.isEnabled {
            guard let key = variable.envKey else { continue }
            set[key] = EnvValue(variable.value)
        }

        let header = [
            "Generated by HyperEnv",
            "Project: \(profile.project?.name ?? "—")  Profile: \(profile.name)",
            "Contains secrets — do not commit this file.",
        ]
        let (text, diagnostics) = DotenvCodec.encode(set, dialect: dialect, headerComment: header)

        let panel = NSSavePanel()
        panel.nameFieldStringValue = ".env.\(profile.name.lowercased())"
        panel.message = "Export \(profile.name) as \(dialect.displayName)"
        panel.canCreateDirectories = true

        if let folder = profile.project?.folderPath {
            panel.directoryURL = URL(fileURLWithPath: folder)
        }

        guard panel.runModal() == .OK, let url = panel.url else { return }

        // NSSavePanel already confirms replacement, but a `.env` in a project
        // folder usually holds live credentials, so the previous contents are
        // preserved before anything is written.
        if FileManager.default.fileExists(atPath: url.path(percentEncoded: false)) {
            pendingOverwrite = PendingOverwrite(url: url, text: text)
            alertTitle = "Replace \(url.lastPathComponent)?"
            alertMessage = "The current contents will be copied to \(url.lastPathComponent).bak first."
            return
        }

        write(text, to: url, extraWarnings: diagnostics)
    }

    func commitOverwrite(_ pending: PendingOverwrite) {
        let backup = pending.url.appendingPathExtension("bak")
        try? FileManager.default.removeItem(at: backup)
        try? FileManager.default.copyItem(at: pending.url, to: backup)

        pendingOverwrite = nil
        write(pending.text, to: pending.url, extraWarnings: [])
    }

    private func write(_ text: String, to url: URL, extraWarnings: [DotenvDiagnostic]) {
        do {
            try text.write(to: url, atomically: true, encoding: .utf8)
            try? FileManager.default.setAttributes(
                [.posixPermissions: NSNumber(value: Int16(0o600))],
                ofItemAtPath: url.path(percentEncoded: false))

            var notes = extraWarnings.map(\.message)
            if let warning = gitignoreWarning(for: url) { notes.append(warning) }

            alertTitle = "Exported"
            alertMessage = notes.isEmpty
                ? "Written to \(Paths.displayPath(url))."
                : ("Written to \(Paths.displayPath(url)).\n\n" + notes.joined(separator: "\n"))
            showsAlert = true
        } catch {
            alertTitle = "Export failed"
            alertMessage = error.localizedDescription
            showsAlert = true
        }
    }

    /// Cheap check with high payoff: an exported `.env` that git is not
    /// ignoring is a credential leak waiting to be committed.
    private func gitignoreWarning(for url: URL) -> String? {
        let folder = url.deletingLastPathComponent()
        let gitignore = folder.appending(path: ".gitignore")
        let isRepo = FileManager.default.fileExists(
            atPath: folder.appending(path: ".git").path(percentEncoded: false))
        guard isRepo else { return nil }

        guard let contents = try? String(contentsOf: gitignore, encoding: .utf8) else {
            return "⚠︎ This folder is a git repository with no .gitignore. Add one before committing."
        }

        let covered = contents.split(separator: "\n").contains { line in
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            return trimmed == ".env" || trimmed == ".env*" || trimmed == "*.env"
                || trimmed == url.lastPathComponent
        }
        return covered ? nil : "⚠︎ .gitignore does not appear to cover this file."
    }

    // MARK: Import

    func beginImport() {
        let panel = NSOpenPanel()
        panel.canChooseFiles = true
        panel.canChooseDirectories = false
        panel.allowsMultipleSelection = false
        panel.message = "Choose a .env file to import"
        panel.showsHiddenFiles = true

        guard panel.runModal() == .OK, let url = panel.url else { return }

        do {
            let text = try String(contentsOf: url, encoding: .utf8)
            pendingImport = PendingImport(
                fileName: url.lastPathComponent,
                result: DotenvCodec.decode(text))
        } catch {
            alertTitle = "Could not read that file"
            alertMessage = "\(url.lastPathComponent) is not valid UTF-8 text."
            showsAlert = true
        }
    }
}

// MARK: - Import preview

struct ImportPreviewSheet: View {
    let pending: DotenvTransfer.PendingImport
    var onCommit: ([DotenvEntry]) -> Void

    @Environment(\.dismiss) private var dismiss
    @State private var excluded: Set<String> = []

    private var included: [DotenvEntry] {
        pending.result.entries.filter { !excluded.contains($0.key.rawValue) }
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            VStack(alignment: .leading, spacing: 4) {
                Text("Import \(pending.fileName)").font(.headline)
                // Shown before committing because a `#` inside an unquoted
                // value is ambiguous and can silently truncate what gets
                // imported — the user should see the parse, not trust it.
                Text("Review what HyperEnv read from the file.")
                    .font(.caption).foregroundStyle(.secondary)
            }
            .padding(16)

            Divider()

            if pending.result.entries.isEmpty {
                ContentUnavailableView(
                    "Nothing to import", systemImage: "doc.text",
                    description: Text("No valid assignments were found."))
                    .frame(height: 180)
            } else {
                List {
                    ForEach(pending.result.entries, id: \.key.rawValue) { entry in
                        HStack(spacing: 10) {
                            Toggle("", isOn: .init(
                                get: { !excluded.contains(entry.key.rawValue) },
                                set: { keep in
                                    if keep { excluded.remove(entry.key.rawValue) }
                                    else { excluded.insert(entry.key.rawValue) }
                                }))
                            .labelsHidden()

                            Text(entry.key.rawValue)
                                .font(.system(.body, design: .monospaced))
                                .frame(width: 190, alignment: .leading)

                            Text(entry.value.rawValue.isEmpty ? "(empty)" : entry.value.rawValue)
                                .font(.system(.body, design: .monospaced))
                                .foregroundStyle(entry.value.isEmpty ? .secondary : .primary)
                                .lineLimit(1)

                            Spacer()
                            Text("line \(entry.line)")
                                .font(.caption2).foregroundStyle(.tertiary)
                        }
                    }
                }
                .frame(height: 240)
            }

            if !pending.result.diagnostics.isEmpty {
                Divider()
                ScrollView {
                    VStack(alignment: .leading, spacing: 4) {
                        ForEach(pending.result.diagnostics) { diagnostic in
                            HStack(alignment: .top, spacing: 6) {
                                Image(systemName: diagnostic.severity == .error
                                      ? "xmark.octagon.fill" : "exclamationmark.triangle.fill")
                                    .foregroundStyle(diagnostic.severity == .error ? .red : .orange)
                                    .font(.caption)
                                Text("Line \(diagnostic.line): \(diagnostic.message)")
                                    .font(.caption)
                                Spacer()
                            }
                        }
                    }
                    .padding(12)
                }
                .frame(maxHeight: 110)
            }

            Divider()

            HStack {
                Text("\(included.count) of \(pending.result.entries.count) selected")
                    .font(.caption).foregroundStyle(.secondary)
                Spacer()
                Button("Cancel") { dismiss() }
                Button("Import") {
                    onCommit(included)
                    dismiss()
                }
                .buttonStyle(.glassProminent)
                .disabled(included.isEmpty)
            }
            .padding(16)
        }
        .frame(width: 620)
    }
}
