//
//  SeedFilter.swift
//  hyperenv
//
//  Decides which of the machine's existing variables belong in the Default
//  profile.
//
//  Everything is bucketed rather than discarded: drift comparison later needs
//  to know a variable was *seen and deliberately excluded*, not merely absent.
//

import Foundation

nonisolated enum SeedBucket: String, Sendable, Codable, CaseIterable {
    /// Real user configuration. These are what the Default profile shows.
    case user
    /// Produced by tooling rather than authored (`brew shellenv`, etc).
    case derived
    /// Valid right now, meaningless later. Replaying these points at dead paths.
    case session
    /// Colon-separated search paths. Never snapshot wholesale.
    case pathLike
    /// Prompt and terminal bookkeeping.
    case cosmetic
    /// Refused outright — writing these back would break things.
    case rejected

    var isImportable: Bool { self == .user }

    var explanation: String {
        switch self {
        case .user: "Your configuration."
        case .derived: "Generated by a tool (such as brew shellenv) rather than set by you."
        case .session: "Valid only for the current login session; replaying it later would point at a path that no longer exists."
        case .pathLike: "A search path. HyperEnv manages these as prepend/append fragments instead of freezing the whole value."
        case .cosmetic: "Terminal and prompt bookkeeping."
        case .rejected: "Cannot be set safely by HyperEnv."
        }
    }
}

nonisolated enum SeedFilter {

    /// Exact names that are per-session and must never be replayed.
    ///
    /// `TMPDIR` is a `/var/folders/<uuid>` path and `SSH_AUTH_SOCK` is a
    /// `/var/run/com.apple.launchd.<random>/Listeners` socket — both are
    /// recreated with different names on the next login.
    private static let sessionScoped: Set<String> = [
        "TMPDIR", "SSH_AUTH_SOCK", "SSH_AGENT_PID", "SSH_CLIENT", "SSH_CONNECTION", "SSH_TTY",
        "SECURITYSESSIONID", "Apple_PubSub_Socket_Render", "XPC_FLAGS", "XPC_SERVICE_NAME",
        "COMMAND_MODE", "MallocNanoZone", "OSLogRateLimit",
        "NoDefaultCurrentDirectoryInExePath",
    ]

    /// Identity of the account itself — never HyperEnv's to manage.
    private static let identity: Set<String> = [
        "HOME", "USER", "LOGNAME", "SHELL", "PWD", "OLDPWD", "USERNAME",
    ]

    private static let pathLike: Set<String> = [
        "PATH", "FPATH", "MANPATH", "INFOPATH", "PKG_CONFIG_PATH",
        "DYLD_FALLBACK_LIBRARY_PATH", "CPATH", "LIBRARY_PATH",
    ]

    private static let cosmetic: Set<String> = [
        "_", "SHLVL", "PS1", "PS2", "PROMPT", "RPROMPT", "TERM", "COLORTERM",
        "TERM_PROGRAM", "TERM_PROGRAM_VERSION", "TERM_SESSION_ID",
        "ITERM_SESSION_ID", "ITERM_PROFILE", "WINDOWID", "COLUMNS", "LINES",
        "LC_TERMINAL", "LC_TERMINAL_VERSION", "EDITOR_TERM",
    ]

    private static let cosmeticPrefixes = ["__CF", "__", "LC_TERMINAL"]
    private static let derivedPrefixes = ["HOMEBREW_"]

    /// `DYLD_*` is stripped by SIP for protected processes and setting it can
    /// break signed binaries, so it is shown but never written.
    private static let rejectedPrefixes = ["DYLD_"]

    static func classify(key: EnvKey, value: EnvValue) -> SeedBucket {
        let name = key.rawValue

        if rejectedPrefixes.contains(where: name.hasPrefix) { return .rejected }
        if pathLike.contains(name) { return .pathLike }
        if sessionScoped.contains(name) || identity.contains(name) { return .session }
        if cosmetic.contains(name) { return .cosmetic }
        if cosmeticPrefixes.contains(where: name.hasPrefix) { return .cosmetic }
        if derivedPrefixes.contains(where: name.hasPrefix) { return .derived }

        // A value that is itself a colon-joined list of existing directories is
        // almost certainly a search path under a name we do not know yet.
        if name.hasSuffix("PATH"), value.rawValue.contains(":") { return .pathLike }

        return .user
    }

    struct Classification: Sendable {
        var buckets: [SeedBucket: EnvSet]

        var importable: EnvSet { buckets[.user] ?? EnvSet() }

        func set(for bucket: SeedBucket) -> EnvSet { buckets[bucket] ?? EnvSet() }
    }

    /// Base-subtraction.
    ///
    /// The probe shell inherits whatever environment the app was launched with,
    /// so the raw output is a mixture of the user's shell configuration and the
    /// app's own launchd inheritance. Subtracting the base the probe was given
    /// isolates what the *shell* contributed, while still keeping any variable
    /// the shell assigned a different value to.
    static func classify(observed: EnvSet, base: EnvSet) -> Classification {
        var buckets: [SeedBucket: EnvSet] = [:]

        for (key, value) in observed.pairs {
            if let baseValue = base[key], baseValue == value { continue }
            let bucket = classify(key: key, value: value)
            var set = buckets[bucket] ?? EnvSet()
            set[key] = value
            buckets[bucket] = set
        }

        return Classification(buckets: buckets)
    }
}
