//
//  SessionScriptRenderer.swift
//  hyperenv
//
//  Renders the two generated shell scripts.
//

import Foundation

nonisolated enum SessionScriptRenderer {

    /// Set this in the environment to make `session.zsh` return immediately.
    ///
    /// This one line is what makes everything else possible: baseline capture,
    /// drift detection and re-sync all need to observe the user's shell *as if
    /// HyperEnv were not installed*, and this lets them do that without moving,
    /// renaming or temporarily deleting the user's files.
    static let bypassVariable = "HYPERENV_DISABLE"

    private static func header(_ lines: [String]) -> [String] {
        ["# Generated by HyperEnv. Do not edit — changes are overwritten on apply."]
            + lines.map { "# \($0)" }
    }

    /// The file sourced by the guarded block in `~/.zprofile`.
    ///
    /// Only exports appear here. A key the previous profile set but this one
    /// does not is simply absent: a *new* shell never had it, so the user's own
    /// value (assigned earlier in their dotfiles) stands unmodified.
    static func renderSession(
        variables: EnvSet,
        projectName: String,
        profileName: String,
        appliedAt: String
    ) -> String {
        var lines = header([
            "Project: \(projectName)",
            "Profile: \(profileName)",
            "Applied: \(appliedAt)",
        ])

        lines += [
            "",
            "[[ -n \"$\(bypassVariable)\" ]] && return",
            "",
        ]

        for (key, value) in variables.pairs {
            lines.append("export \(key.rawValue)=\(ShellQuoting.singleQuote(value.rawValue))")
        }

        return lines.joined(separator: "\n") + "\n"
    }

    /// The inverse script, for shells that are *already open* and have already
    /// sourced a session file. Sourcing cannot un-export anything, so the undo
    /// has to be materialised explicitly.
    ///
    /// Generated at apply time rather than at un-apply time, so it stays valid
    /// even if HyperEnv is deleted before the user gets around to reverting.
    static func renderInverse(
        restoring entries: [(key: EnvKey, prior: PriorState)],
        appliedAt: String
    ) -> String {
        var lines = header([
            "Undoes the environment applied at \(appliedAt).",
            "Run: source ~/.config/hyperenv/unsession.zsh",
        ])
        lines.append("")

        for (key, prior) in entries.sorted(by: { $0.key < $1.key }) {
            switch prior {
            case .absent:
                lines.append("unset \(key.rawValue)")
            case .present(let value):
                lines.append("export \(key.rawValue)=\(ShellQuoting.singleQuote(value.rawValue))")
            }
        }

        return lines.joined(separator: "\n") + "\n"
    }

    /// The body of the guarded block written into `~/.zprofile`.
    static func hookBody(sessionPath: String) -> [String] {
        ["[ -r \"\(sessionPath)\" ] && . \"\(sessionPath)\""]
    }
}
