// Turns design/ — the one source of HyperEnv 2's visual language — into what
// the macOS app compiles: hyperenv/Design/Tokens.swift and one template
// imageset per icon in Assets.xcassets/Icons. Run by generate-design.sh;
// the outputs are committed, and regenerated whenever design/ changes.

import Foundation

let args = CommandLine.arguments
guard args.count == 3 else {
    FileHandle.standardError.write("usage: GenerateDesign <design-dir> <app-sources-dir>\n".data(using: .utf8)!)
    exit(2)
}
let design = URL(fileURLWithPath: args[1])
let app = URL(fileURLWithPath: args[2])

let tokens = try JSONSerialization.jsonObject(
    with: Data(contentsOf: design.appending(path: "tokens.json"))) as! [String: Any]

func camel(_ s: String) -> String { s }
func hex(_ s: String) -> String {
    let h = s.dropFirst()
    return "0x" + h
}

var out = """
// Generated by Scripts/generate-design.sh from design/tokens.json. Do not edit.

import SwiftUI

/// HyperEnv 2's design tokens — the same values the Windows and Linux app is
/// built from. Colours resolve per appearance (light and dark).
enum Tokens {

"""

let colors = tokens["color"] as! [String: [String: String]]
for name in colors.keys.sorted() {
    let pair = colors[name]!
    out += "    static let \(camel(name)) = Color(light: \(hex(pair["light"]!)), dark: \(hex(pair["dark"]!)))\n"
}
out += "\n"
for (group, prefix) in [("size", "size"), ("radius", "radius"), ("layout", "")] {
    let values = tokens[group] as! [String: Any]
    for name in values.keys.sorted() {
        let id = prefix.isEmpty ? name : prefix + name.prefix(1).uppercased() + name.dropFirst()
        out += "    static let \(id): CGFloat = \(values[name]!)\n"
    }
    out += "\n"
}
let fonts = tokens["font"] as! [String: [String: Any]]
out += "    static let fontUI = \"\(fonts["ui"]!["family"]!)\"\n"
out += "    static let fontMono = \"\(fonts["mono"]!["family"]!)\"\n"
out += "}\n"

let designDir = app.appending(path: "Design")
try FileManager.default.createDirectory(at: designDir, withIntermediateDirectories: true)
try out.write(to: designDir.appending(path: "Tokens.swift"), atomically: true, encoding: .utf8)

// Icons: one vector imageset each, rendered as a template so it takes the
// foreground colour like text does.
let iconsDir = app.appending(path: "Assets.xcassets/Icons")
try? FileManager.default.removeItem(at: iconsDir)
try FileManager.default.createDirectory(at: iconsDir, withIntermediateDirectories: true)
try #"{ "info": { "author": "xcode", "version": 1 }, "properties": { "provides-namespace": true } }"#
    .write(to: iconsDir.appending(path: "Contents.json"), atomically: true, encoding: .utf8)
let svgs = try FileManager.default.contentsOfDirectory(
    at: design.appending(path: "icons"), includingPropertiesForKeys: nil
).filter { $0.pathExtension == "svg" }.sorted { $0.path < $1.path }
for svg in svgs {
    let name = svg.deletingPathExtension().lastPathComponent
    let set = iconsDir.appending(path: "\(name).imageset")
    try FileManager.default.createDirectory(at: set, withIntermediateDirectories: true)
    try FileManager.default.copyItem(at: svg, to: set.appending(path: "\(name).svg"))
    try """
    {
      "images": [{ "filename": "\(name).svg", "idiom": "universal" }],
      "info": { "author": "xcode", "version": 1 },
      "properties": { "preserves-vector-representation": true, "template-rendering-intent": "template" }
    }
    """.write(to: set.appending(path: "Contents.json"), atomically: true, encoding: .utf8)
}
print("Tokens.swift and \(svgs.count) icons written")
