// Generated by Scripts/generate-design.sh from design/tokens.json. Do not edit.

import SwiftUI

/// HyperEnv 2's design tokens — the same values the Windows and Linux app is
/// built from. Colours resolve per appearance (light and dark).
enum Tokens {
    static let accent = Color(light: 0x5C44E6, dark: 0x8B7BFF)
    static let error = Color(light: 0xC0392B, dark: 0xFF5A4E)
    static let ground = Color(light: 0xE9E7F6, dark: 0x0B0A1A)
    static let ink = Color(light: 0x15123A, dark: 0xEEEDFB)
    static let line = Color(light: 0xDDD9F5, dark: 0x2C2850)
    static let lineSoft = Color(light: 0xECEAF8, dark: 0x221F40)
    static let live = Color(light: 0x1E8A4C, dark: 0x3DD47A)
    static let liveBg = Color(light: 0xE2F4E8, dark: 0x12291D)
    static let liveText = Color(light: 0x155C33, dark: 0xA6EBC2)
    static let masked = Color(light: 0x8C89AD, dark: 0x6E6A99)
    static let muted = Color(light: 0x5D5A85, dark: 0xA09DC4)
    static let onAccent = Color(light: 0xFFFFFF, dark: 0x15132B)
    static let pending = Color(light: 0xB86A00, dark: 0xFF9F1C)
    static let pendingBg = Color(light: 0xFDF0DC, dark: 0x2E2410)
    static let pendingText = Color(light: 0x7A4600, dark: 0xFFD08A)
    static let raised = Color(light: 0xFCFBFF, dark: 0x1E1B3A)
    static let sidebar = Color(light: 0xF5F4FD, dark: 0x100E22)
    static let surface = Color(light: 0xFCFBFF, dark: 0x15132B)

    static let sizeBody: CGFloat = 13
    static let sizeCaption: CGFloat = 11
    static let sizeHeading: CGFloat = 20
    static let sizeSmall: CGFloat = 12
    static let sizeTitle: CGFloat = 28
    static let sizeUi: CGFloat = 14

    static let radiusLg: CGFloat = 12
    static let radiusMd: CGFloat = 8
    static let radiusSm: CGFloat = 6
    static let radiusXs: CGFloat = 4

    static let keyColumn: CGFloat = 300
    static let rowHeight: CGFloat = 48
    static let sidebarWidth: CGFloat = 288
    static let statusbarHeight: CGFloat = 32
    static let titlebarHeight: CGFloat = 44

    static let fontUI = "Schibsted Grotesk"
    static let fontMono = "JetBrains Mono"
}
