//! Generates `tokens.slint` from `design/tokens.json`, the one source of the
//! visual language, so the window cannot drift from the macOS app or the
//! mockups. The icons are read straight from `design/icons/`.

use std::fmt::Write;
use std::path::PathBuf;

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let design = manifest.join("../../design");
    let tokens_path = design.join("tokens.json");
    println!("cargo:rerun-if-changed={}", tokens_path.display());
    println!("cargo:rerun-if-changed={}", design.join("icons").display());

    let tokens: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(&tokens_path).unwrap()).unwrap();

    let mut out = String::from(
        "// Generated by apps/desktop/build.rs from design/tokens.json. Do not edit.\n\
         import { Palette } from \"std-widgets.slint\";\n\n\
         export global Tokens {\n\
         \x20   out property <bool> dark: Palette.color-scheme == ColorScheme.dark;\n",
    );
    for (name, pair) in tokens["color"].as_object().unwrap() {
        let light = pair["light"].as_str().unwrap();
        let dark = pair["dark"].as_str().unwrap();
        writeln!(
            out,
            "    out property <color> {}: dark ? {dark} : {light};",
            kebab(name)
        )
        .unwrap();
    }
    for (name, v) in tokens["size"].as_object().unwrap() {
        writeln!(out, "    out property <length> size-{}: {}px;", kebab(name), v).unwrap();
    }
    for (name, v) in tokens["radius"].as_object().unwrap() {
        writeln!(out, "    out property <length> radius-{}: {}px;", kebab(name), v).unwrap();
    }
    for (name, v) in tokens["layout"].as_object().unwrap() {
        writeln!(out, "    out property <length> {}: {}px;", kebab(name), v).unwrap();
    }
    writeln!(
        out,
        "    out property <string> font-ui: \"{}\";",
        tokens["font"]["ui"]["family"].as_str().unwrap()
    )
    .unwrap();
    writeln!(
        out,
        "    out property <string> font-mono: \"{}\";",
        tokens["font"]["mono"]["family"].as_str().unwrap()
    )
    .unwrap();
    out.push_str("}\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    std::fs::write(out_dir.join("tokens.slint"), out).unwrap();

    let config = slint_build::CompilerConfiguration::new().with_include_paths(vec![out_dir]);
    slint_build::compile_with_config("ui/app.slint", config).unwrap();
}

fn kebab(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c.is_ascii_uppercase() {
            out.push('-');
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}
