//! The generated scripts, in each shell dialect.
//!
//! Two per apply: the session script (what new terminals load) and its inverse
//! (to undo in a terminal that was already open).

use crate::quoting::{fish_single, posix_single, powershell_single};
use crate::types::{EnvKey, EnvSet, PriorState};

/// Set this in the environment to make the session script do nothing.
///
/// This one line is what makes everything else possible: baseline capture,
/// drift detection and re-sync all need to observe the user's shell *as if
/// HyperEnv were not installed*, without moving or renaming the user's files.
pub const BYPASS_VARIABLE: &str = "HYPERENV_DISABLE";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Shell {
    Zsh,
    Bash,
    Fish,
    /// Windows: the persistent environment goes through the registry; the
    /// script applies or undoes it in a PowerShell that was already open.
    PowerShell,
}

impl Shell {
    /// Extension of the generated script (`session.zsh`, `unsession.fish`…).
    pub fn extension(self) -> &'static str {
        match self {
            Shell::Zsh => "zsh",
            Shell::Bash => "bash",
            Shell::Fish => "fish",
            Shell::PowerShell => "ps1",
        }
    }

    /// Recognises the shell from its executable path (`/bin/zsh`, `fish`…).
    pub fn from_path(path: &str) -> Option<Shell> {
        let name = path.rsplit(['/', '\\']).next().unwrap_or(path);
        let name = name.strip_suffix(".exe").unwrap_or(name);
        match name {
            "zsh" => Some(Shell::Zsh),
            "bash" => Some(Shell::Bash),
            "fish" => Some(Shell::Fish),
            "pwsh" | "powershell" => Some(Shell::PowerShell),
            _ => None,
        }
    }

    fn comment(self) -> &'static str {
        "#"
    }

    fn export_line(self, key: &EnvKey, value: &str) -> String {
        match self {
            Shell::Zsh | Shell::Bash => format!("export {key}={}", posix_single(value)),
            Shell::Fish => format!("set -gx {key} {}", fish_single(value)),
            Shell::PowerShell => format!("$env:{key} = {}", powershell_single(value)),
        }
    }

    fn unset_line(self, key: &EnvKey) -> String {
        match self {
            Shell::Zsh | Shell::Bash => format!("unset {key}"),
            Shell::Fish => format!("set -e {key}"),
            Shell::PowerShell => format!("Remove-Item Env:{key} -ErrorAction SilentlyContinue"),
        }
    }

    /// Opens the section that only runs without the bypass. POSIX returns
    /// early; fish and PowerShell wrap the lines in an `if`, because `return`
    /// outside a function is not reliable in them.
    fn guard_open(self) -> &'static str {
        match self {
            Shell::Zsh | Shell::Bash => "[[ -n \"$HYPERENV_DISABLE\" ]] && return",
            Shell::Fish => "if test -z \"$HYPERENV_DISABLE\"",
            Shell::PowerShell => "if (-not $env:HYPERENV_DISABLE) {",
        }
    }

    fn guard_close(self) -> Option<&'static str> {
        match self {
            Shell::Zsh | Shell::Bash => None,
            Shell::Fish => Some("end"),
            Shell::PowerShell => Some("}"),
        }
    }

    fn indent(self) -> &'static str {
        match self {
            Shell::Zsh | Shell::Bash => "",
            Shell::Fish | Shell::PowerShell => "    ",
        }
    }

    /// The line the user's startup file uses to load the session script.
    pub fn hook_body(self, session_path: &str) -> Vec<String> {
        match self {
            Shell::Zsh | Shell::Bash => {
                vec![format!("[ -r \"{session_path}\" ] && . \"{session_path}\"")]
            }
            Shell::Fish => vec![format!(
                "test -r \"{session_path}\"; and source \"{session_path}\""
            )],
            Shell::PowerShell => {
                vec![format!(
                    "if (Test-Path \"{session_path}\") {{ . \"{session_path}\" }}"
                )]
            }
        }
    }
}

fn header(shell: Shell, notes: &[String]) -> Vec<String> {
    let c = shell.comment();
    let mut lines = vec![format!(
        "{c} Generated by HyperEnv. Do not edit — changes are overwritten on apply."
    )];
    lines.extend(notes.iter().map(|n| format!("{c} {n}")));
    lines
}

fn finish(lines: Vec<String>) -> String {
    let mut out = lines.join("\n");
    out.push('\n');
    out
}

/// The session script.
///
/// Only exports appear here. A key the previous profile set but this one does
/// not is simply absent: a *new* shell never had it, so the user's own value
/// (assigned earlier in their dotfiles) stands unmodified.
pub fn session(shell: Shell, variables: &EnvSet, profile: &str, applied_at: &str) -> String {
    let mut lines = header(
        shell,
        &[format!("Profile: {profile}"), format!("Applied: {applied_at}")],
    );
    lines.push(String::new());
    lines.push(shell.guard_open().to_owned());
    if shell.guard_close().is_none() {
        lines.push(String::new());
    }
    for (key, value) in variables.iter() {
        lines.push(format!(
            "{}{}",
            shell.indent(),
            shell.export_line(key, value.as_str())
        ));
    }
    if let Some(close) = shell.guard_close() {
        lines.push(close.to_owned());
    }
    finish(lines)
}

/// The inverse script, for shells that are *already open* and have already
/// loaded a session. Loading a script cannot un-export anything, so the undo
/// has to be written out explicitly.
///
/// Generated at apply time rather than at un-apply time, so it stays valid
/// even if HyperEnv is deleted before the user gets around to reverting.
pub fn inverse(shell: Shell, entries: &[(EnvKey, PriorState)], applied_at: &str, path: &str) -> String {
    let mut lines = header(
        shell,
        &[
            format!("Undoes the environment applied at {applied_at}."),
            format!("Run: {}", source_command(shell, path)),
        ],
    );
    lines.push(String::new());
    let mut sorted: Vec<&(EnvKey, PriorState)> = entries.iter().collect();
    sorted.sort_by(|a, b| a.0.cmp(&b.0));
    for (key, prior) in sorted {
        lines.push(match prior {
            PriorState::Absent => shell.unset_line(key),
            PriorState::Present(v) => shell.export_line(key, v.as_str()),
        });
    }
    finish(lines)
}

/// How the user loads a script into the current shell.
pub fn source_command(shell: Shell, path: &str) -> String {
    match shell {
        Shell::Zsh | Shell::Bash | Shell::Fish => format!("source {path}"),
        Shell::PowerShell => format!(". \"{path}\""),
    }
}
